### ISSUE TITLE
vs2022用不了

### ISSUE THREAD

**Issue by getsync** [lvtx/OLEDLG-for-Visual-Assist-X#3]
vs2022_64 + VA_X_Setup2440_0 不能用，dll 放到目录未加载

**Comment by Lioncky** [comment]
> vs2022_64 + VA_X_Setup2440_0 不能用，dll 放到目录未加载

vs22无限试用可以的

**Comment by qiangxinglin** [comment]
PYG上有oledlg的, 但不是通杀, 而且没法64 86的共存

**Comment by number201724** [comment]
[VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12420257/VisualAssist-Patcher.zip)

**Comment by Helesta0731** [comment]
[VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)

用C++重写了一份，支持了VS2022，支持最新版VAX
License在README.txt

**Comment by qiangxinglin** [comment]
> [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> 
> 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt

KeyGen 可以一块发下么?

**Comment by Helesta0731** [comment]
> > [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> > 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt
> 
> KeyGen 可以一块发下么?

自己找

**Comment by qiangxinglin** [comment]
>


> > > [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> > > 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt
> > 
> > 
> > KeyGen 可以一块发下么?
> 
> 自己找

你的实现里用了新的私钥, 哪里找得到...

**Comment by lvtx** [comment]
> 

GitHub 这边被屏蔽了，去 [Gitee](https://gitee.com/wiflvtx/VisualAssist-keygen-demo) 哪边有KeyGen

**Comment by lvtx** [comment]
> [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> 
> 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt

感谢分享，我C++自学功底比较差，写的O(∩_∩)O我自己都不忍直视……哈哈！

**Comment by lvtx** [comment]
> > 
> 
> > > > [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> > > > 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt
> > > 
> > > 
> > > KeyGen 可以一块发下么?
> > 
> > 
> > 自己找
> 
> 你的实现里用了新的私钥, 哪里找得到...

GitHub 这边被屏蔽了，去 Gitee 哪边有 [VisualAssist-keygen-demo](https://gitee.com/wiflvtx/VisualAssist-keygen-demo)

**Comment by qiangxinglin** [comment]
> > > 
> > 
> > 
> > > > > [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> > > > > 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt
> > > > 
> > > > 
> > > > KeyGen 可以一块发下么?
> > > 
> > > 
> > > 自己找
> > 
> > 
> > 你的实现里用了新的私钥, 哪里找得到...
> 
> GitHub 这边被屏蔽了，去 Gitee 哪边有 [VisualAssist-keygen-demo](https://gitee.com/wiflvtx/VisualAssist-keygen-demo)

gitee那边的G是2127088620, 这份压缩包里的G是跟官方一样的1329115615, 所以配套的私钥很关键

**Comment by Helesta0731** [comment]
> > > > 
> > > 
> > > 
> > > > > > [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> > > > > > 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt
> > > > > 
> > > > > 
> > > > > KeyGen 可以一块发下么?
> > > > 
> > > > 
> > > > 自己找
> > > 
> > > 
> > > 你的实现里用了新的私钥, 哪里找得到...
> > 
> > 
> > GitHub 这边被屏蔽了，去 Gitee 哪边有 [VisualAssist-keygen-demo](https://gitee.com/wiflvtx/VisualAssist-keygen-demo)
> 
> gitee那边的G是2127088620, 这份压缩包里的G是跟官方一样的1329115615, 所以配套的私钥很关键

这私钥是我用52pojie随便找的一个人发的抠的私钥 我也没keygen
我只是单纯的翻译成了x64以方便支持2022

顺便我怕大号被DMCA打，单独开了个github小号……

**Comment by lvtx** [comment]
> > > > 
> > > 
> > > 
> > > > > > [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> > > > > > 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt
> > > > > 
> > > > > 
> > > > > KeyGen 可以一块发下么?
> > > > 
> > > > 
> > > > 自己找
> > > 
> > > 
> > > 你的实现里用了新的私钥, 哪里找得到...
> > 
> > 
> > GitHub 这边被屏蔽了，去 Gitee 哪边有 [VisualAssist-keygen-demo](https://gitee.com/wiflvtx/VisualAssist-keygen-demo)
> 
> gitee那边的G是2127088620, 这份压缩包里的G是跟官方一样的1329115615, 所以配套的私钥很关键

办法总比困难多~ 明白原理的话，就是要找到VX原始的PublicKey并进行替换，简单修改一下代码就可以继续用自己的KEY了！

![000](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/28129c1e-5f4c-49bd-bfef-ac9685e33f6e)

![002](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/520ff465-5823-4ee4-85f6-1093c023d304)

![001](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/650f73fd-7ae6-4b6a-8c51-6fedeeee7088)

**Comment by qiangxinglin** [comment]
@lvtx @AzumaSeren 用第二原像的方法跑了1天, 试出了一对, 送给有缘人
`cDE6IDB4MmRlZjY2YzdmNjNjMDQ3YzJlN2FiYWE5Mzc4NApwMjogMHgyZGVmNjZjN2Y2M2MwNDdjMmU3ZmY2NmU4ZDJj`

**Comment by lvtx** [comment]
> @lvtx @AzumaSeren 用第二原像的方法跑了1天, 试出了一对, 送给有缘人 `cDE6IDB4MmRlZjY2YzdmNjNjMDQ3YzJlN2FiYWE5Mzc4NApwMjogMHgyZGVmNjZjN2Y2M2MwNDdjMmU3ZmY2NmU4ZDJj`

果然好使！O(∩_∩)O哈哈~

![0001](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/9912f92f-b421-421d-a9ea-76a1f9c60fd9)
![0002](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/7680c3b1-1c24-4146-b052-a7952e035843)
![0003](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/9c0be089-fc40-4ad3-86e5-fa10646c592c)
![0004](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/assets/12689101/534cb56c-6934-469a-9b6c-47a53217bf4b)

**Comment by luodaoyi** [comment]
现在好像不能用了 2522我编译了一份OLEDLG ， 放进IDE 目录直接没反应

**Comment by august295** [comment]
> [VisualAssist-Patcher.zip](https://github.com/lvtx/OLEDLG-for-Visual-Assist-X/files/12429651/VisualAssist-Patcher.zip)
> 
> 用C++重写了一份，支持了VS2022，支持最新版VAX License在README.txt

我的环境是 `VS2022+VA_X_Setup2500_0.exe[10.9.2500/2023.08.24]`，我使用上述文件编译得到 `oledlg.dll` 以及文件中的 `Key`，可以激活，但是我是用作者 https://gitee.com/wiflvtx/VisualAssist-keygen-demo 的密钥生成器不能成功，`PublicKey` 我也是用作者的进行了对应替换，请问怎么操作

**Comment by qiangxinglin** [comment]
@august295 vs2022是64位的, 不能用oledlg, 要替vcruntime

**Comment by august295** [comment]
> @august295 vs2022是64位的, 不能用oledlg, 要替vcruntime

应该是可以的，https://www.winsec.cn/ 该网址激活就是使用 `oledlg`，能够激活最新版 `VS2022+VA_X_Setup2522_0.exe`，我就是不知道公钥，密钥，HASH之间的关系，以及如何替换不知道这其中的原理，感觉是没对应上，可以留个联系方式进行请教一下吗？微信：base64(MTUxODI5MzMwNTE=)

**Comment by ZenTypeCPU** [comment]
I tested that winsec.cn and it seems to work registering with the provided info, using the oledlg.dll. I tested only in sandbox, but the dll seems to be pretty big and that makes me wonder why is so complicated. So I dont trust it.
And using the info provided here by lvtx and also on the gitee I wasnt able to register properly, in theory I understand what I should do I believe, basically trying to override their public and secret key, then registering... but it fails. The oldelg.dll loads, it overwrites the data, but still can't make the plugin register itself.

**Comment by Feng-Teng** [comment]
> > vs2022是64位的， 不能用oledlg， 要替vcruntime
> 
> 应该是可以的，https://www.winsec.cn/ 该网址激活就是使用 ，能够激活最新版 ，我就是不知道公钥，密钥，HASH之间的关系，以及如何替换不知道这其中的原理，感觉是没对应上，可以留个联系方式进行请教一下吗？微信：base64（MTUxODI5MzMwNTE=）`oledlg``VS2022+VA_X_Setup2522_0.exe`

劫持oledlg是可以的，只不过这货把DLL加壳了，还是一样的套路的

**Comment by Feng-Teng** [comment]
> 我测试了那个 winsec.cn，它似乎可以使用 oledlg.dll 使用提供的信息进行注册。我只在沙箱中测试了，但 dll 似乎相当大，这让我想知道为什么这么复杂。所以我不相信它。使用 lvtx 和 gitee 提供的信息，我无法正确注册，理论上我明白我应该做什么，我相信我应该做什么，基本上是试图覆盖他们的公钥和秘密密钥，然后注册......但它失败了。oldelg.dll 加载后，它会覆盖数据，但仍然无法使插件自行注册。

混淆加壳了 肯定大
